commands of docker :-docker pull helloworld docker 
docker run helloworld.
docker run -it ubuntu
exit 
docker stop <id>

container :- image will store here 

Docker Network :-
docker network ls 
docker network create mongo-network 
docker network ls 
docker run -d -p 2701717 -name momgo --network mongo-network -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=admin mongo 


docker network inspect mongo network .

o--name 
o--network 
o-e
running mongo- express 
docker run -d \
  -p 8081:8081 \
  --name mongo-express \
  --network mongo-network \
  -e ME_CONFIG_MONGODB_SERVER=mongo \
  -e ME_CONFIG_MONGODB_PORT=27017 \
  -e ME_CONFIG_MONGODB_ADMINUSERNAME=admin \
  -e ME_CONFIG_MONGODB_ADMINPASSWORD=secret \
  mongo-express
